### PR TITLE
Publish LevelString like ParseLevel

### PR DESCRIPTION
**Pull request by genofire**
#### Changes
What types of changes does your code introduce?

* [ ] Bugfix
* [ ] Tech Debt (fixes an infrastructure issue, code quality issue, etc.)
* [ ] Feature development
* [ ] Other (please explain here)

#### Checklist

* [x] Unit tests, acceptance tests, lint checks, code style checks, etc., all pass

### CODE REVIEW

**Comment by genofire** [comment]
I do not like it to write this duplicated code in in Formeter again ...

**Comment by mkenney** [comment]
Do you mean so that you can use it in your own custom formatters?

**Comment by genofire** [comment]
Yes, a small html one

**Comment by mkenney** [comment]
OK, That makes sense. 

It looks like the build is failing due to lint checks. Please run `golint ./...` and make the suggested updates. You can install golint with `go get -u golang.org/x/lint/golint`

Thanks!

**Comment by genofire** [comment]
sorry, was on github browser editing - now i have a console ;)

**Comment by mkenney** [comment]
Great, thank you! 🎉

**Comment by mkenney** [comment]
This is included in `v0.1.19`.

**Pull request merged**
